//
//  FruitExample_InBuild.swift
//
//
//  Created by Carlyn Maw on 1/17/24.
//
// This file used code generated by MyInBuildPlugin from
// files in Data folder. Please see the README there for more information. 

//import Foundation
import ArgumentParser

//FruitStore is redefined defined in code generated by MyInBuildPlugin
//uncomment this line temporarily to get the IDE to stop complaining
//but build will fail once tool has run if line isn't commented out.
//var FruitStore:Dictionary<String,[any Fruit]> = [:]

protocol Fruit {
    var name:String {get}
}

extension PluginTesterCLI {
    struct fruit_list: ParsableCommand {
        @Argument var fruitType:String?
        
        mutating func run() throws {
            if let fruitType {
                if let  fruitList = FruitStore[fruitType] {
                    print("We have \(fruitList.count) \(fruitType)(s).")
                    fruitList.forEach({print("- \($0.name)")})
                } else {
                 print("No fruit of type \(fruitType) in the FruitStore.")
                }
            } else {
                print("full fruit store")
                print("\(FruitStore)")
            }
            //testVariable is defined in code generated by MyInBuildPlugin
            //this line will fail before the first time it is run.
            print("Hello, \(testVariable)")
        }
    }
}




