//
//  FruitExample_InBuild.swift
//
//
//  Created by Carlyn Maw on 1/17/24.
//
// This file refers to code generated by MyInBuildPlugin from
// files in Data folder. Please see Data/README.md for more information.


import ArgumentParser

//FruitStore is redefined in code generated by MyInBuildPlugin.
//Uncomment this line temporarily to get the IDE to stop complaining
//when you first clone the repo but build will fail once tool has
//run if line isn't commented out.
//var FruitStore:Dictionary<String,[any Fruit]> = [:]

protocol Fruit {
    var name:String {get}
}

extension PluginTesterCLI {
    struct fruit_list: ParsableCommand {
        @Argument var fruitType:String?
        
        mutating func run() throws {
            if let fruitType {
                if let  fruitList = FruitStore[fruitType] {
                    print("We have \(fruitList.count) \(fruitType)(s).")
                    fruitList.forEach({print("- \($0.name)")})
                } else {
                 print("No fruit of type \(fruitType) in the FruitStore.")
                }
            } else {
                print("full fruit store")
                print("\(FruitStore)")
            }
            //testVariable is defined in code generated by MyInBuildPlugin
            //this line will fail until MyInBuildPlugin runs.
            print("Hello, \(testVariable)")
        }
    }
}




